#!/usr/bin/env python3
import sys
import math

def find(n):
    try:
        r = sys.argv[1 + nums.index(n)]
    except Exception:
        return '-'
    return r


nums = []

for n in sys.argv[1:]:
    try:
        f = float(n)
    except Exception:
        continue
    nums.append(f)

if not nums:
    # read from stdin
    line = sys.stdin.readline()
    while line:
        try:
            f = float(line)
        except Exception as e:
            print(e)
            continue
        nums.append(f)
        line = sys.stdin.readline()


sum = 0.0
avg = 0.0
min = 0.0
max = 0.0
sd = 0.0

for f in nums:
    sum += f
    sd += f * f
    if min == 0:
        min = f
    elif f < min:
        min = f

    if f > max:
        max = f
if sum == int(sum):
    sum = int(sum)
min = find(min)
max = find(max)

try:
    avg = sum / len(nums)
    if avg == int(avg):
        avg = int(avg)
except ZeroDivisionError:
    avg = '-'

if len(nums) and avg != '-':
    for f in nums:
        d = avg - f
        d *= d
        sd += d
    sd = math.sqrt(sd / len(nums))
    if sd == int(sd):
        sd = int(sd)
else:
    sd = '-'


print(f"sum: {sum}")
print(f"avg: {sum / len(nums)}")
print(f"sd : {sd}")
print(f"min: {min}")
print(f"max: {max}")
